import {
  Apple,
  Banana,
  Beef,
  Bird,
  Carrot,
  Cherry,
  Citrus,
  Cloud,
  CloudRain,
  CookingPot,
  Droplet,
  Egg,
  Fence,
  Fish,
  Flower,
  Grape,
  Ham,
  Leaf,
  Milk,
  Package,
  Rabbit,
  ShoppingBasket,
  Shovel,
  Shrimp,
  Snail,
  Snowflake,
  Soup,
  Spade,
  Sprout,
  Store,
  Sun,
  Sunrise,
  Tent,
  Tractor,
  TreeDeciduous,
  Trees,
  Utensils,
  Vegan,
  Warehouse,
  Waves,
  Wheat,
  Wind,
  Wine,
  Worm,
  Check,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  egg: Egg,
  cattle: Beef,
  pig: Ham,
  fish: Fish,
  sprout: Sprout,
  feedbag: Wheat,
  carrot: Carrot,
  milk: Milk,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  citrus: Citrus,
  grape: Grape,
  leaf: Leaf,
  flower: Flower,
  tree: TreeDeciduous,
  trees: Trees,
  tractor: Tractor,
  sun: Sun,
  sunrise: Sunrise,
  snowflake: Snowflake,
  droplet: Droplet,
  cloud: Cloud,
  rain: CloudRain,
  wind: Wind,
  store: Store,
  basket: ShoppingBasket,
  warehouse: Warehouse,
  vegan: Vegan,
  wine: Wine,
  soup: Soup,
  spade: Spade,
  shovel: Shovel,
  shrimp: Shrimp,
  snail: Snail,
  rabbit: Rabbit,
  bird: Bird,
  worm: Worm,
  tent: Tent,
  package: Package,
  pot: CookingPot,
  utensils: Utensils,
  fence: Fence,
  waves: Waves,
  check: Check,
};

export type IconOption = { value: string; label: string };

export const ICON_OPTIONS: IconOption[] = [
  { value: "egg", label: "Œuf" },
  { value: "cattle", label: "Bétail" },
  { value: "pig", label: "Porc" },
  { value: "fish", label: "Poisson" },
  { value: "shrimp", label: "Crevette" },
  { value: "snail", label: "Escargot" },
  { value: "rabbit", label: "Lapin" },
  { value: "bird", label: "Volaille" },
  { value: "worm", label: "Ver" },
  { value: "sprout", label: "Pousse" },
  { value: "feedbag", label: "Sac d'aliment" },
  { value: "carrot", label: "Carotte" },
  { value: "apple", label: "Pomme" },
  { value: "banana", label: "Banane" },
  { value: "cherry", label: "Cerise" },
  { value: "citrus", label: "Agrume" },
  { value: "grape", label: "Raisin" },
  { value: "leaf", label: "Feuille" },
  { value: "flower", label: "Fleur" },
  { value: "tree", label: "Arbre" },
  { value: "trees", label: "Forêt" },
  { value: "tractor", label: "Tracteur" },
  { value: "sun", label: "Soleil" },
  { value: "sunrise", label: "Lever de soleil" },
  { value: "snowflake", label: "Flocon" },
  { value: "droplet", label: "Goutte" },
  { value: "cloud", label: "Nuage" },
  { value: "rain", label: "Pluie" },
  { value: "wind", label: "Vent" },
  { value: "store", label: "Boutique" },
  { value: "basket", label: "Panier" },
  { value: "warehouse", label: "Entrepôt" },
  { value: "vegan", label: "Végétal" },
  { value: "wine", label: "Vin" },
  { value: "soup", label: "Soupe" },
  { value: "spade", label: "Bêche" },
  { value: "shovel", label: "Pelle" },
  { value: "tent", label: "Tente" },
  { value: "package", label: "Colis" },
  { value: "pot", label: "Marmite" },
  { value: "utensils", label: "Couverts" },
  { value: "fence", label: "Clôture" },
  { value: "waves", label: "Vagues" },
];

export function CategoryIcon({
  icon,
  size = 18,
  className,
}: {
  icon: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICON_MAP[icon] ?? Sprout;
  return <Icon size={size} className={className} />;
}

export function getCategoryIcon(icon: string): LucideIcon {
  return ICON_MAP[icon] ?? Sprout;
}
